[plugins]

detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[versions]

accompanist = "0.25.1"
android-gradle-plugin = "7.3.0-rc01"
android-core-desugaring = "1.2.2"
androidx-activity-compose = "1.5.1"
androidx-annotation = "1.4.0"
androidx-appcompat = "1.4.1"
androidx-arch = "2.1.0"
androidx-compose = "1.2.1"
androidx-compose-compiler = "1.3.0-beta01"
androidx-core = "1.9.0"
androidx-core-splashscreen = "1.0.0-alpha02"
androidx-espresso = "3.4.0"
androidx-fragment = "1.5.2"
androidx-hilt-navigation-compose = "1.0.0"
androidx-lifecycle = "2.5.1"
androidx-navigation = "2.5.2"
androidx-savedstate = "1.2.0"
androidx-test-core = "1.4.0"
androidx-test-runner = "1.4.0"
androidx-test-rules = "1.4.0"
androidx-test-ext-junit = "1.1.3"
androidx-test-ext-truth = "1.4.0"
coil = "2.2.1"
dagger = "2.43.2"
detekt = "1.21.0"
eithernet = "1.2.1"
expect-kt = "1.0.1"
google-material = "1.5.0"
junit = "4.13.2"
kotlin = "1.7.10"
kotlinx-coroutines = "1.6.4"
ksp = "1.7.10-1.0.6"
ktlint = "0.46.0"
material = "1.4.0"
mockk = "1.12.4"
moshi = "1.14.0"
okhttp = "4.10.0"
openapi-generator = "6.0.1"
play-core = "1.10.3"
play-core-ktx = "1.8.1"
retrofit = "2.9.0"
spotless = "6.10.0"
turbine = "0.9.0"

[libraries]

accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insets-ui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
android-core-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-core-desugaring" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-arch-core = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
androidx-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt-navigation-compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "androidx-savedstate" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "androidx-test-ext-truth" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
eithernet = { module = "com.slack.eithernet:eithernet", version.ref = "eithernet" }
expectKt = { module = "com.nhaarman:expect.kt", version.ref = "expect-kt" }
junit-junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
play-core = { module = "com.google.android.play:core", version.ref = "play-core" }
play-core-ktx = { module = "com.google.android.play:core-ktx", version.ref = "play-core-ktx" }
plugin-agp = { module = "com.android.tools.build:gradle", version.ref = "android-gradle-plugin" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
plugin-kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
